export function FirInitialValues(selectedFir) {
  return {
      submissionDate: selectedFir ? selectedFir.submissionDate : "",
      signedDocument: selectedFir ? selectedFir.signedDocument : null,
      jobNumber: selectedFir ? selectedFir.jobNumber : "",
      bhaNumber: selectedFir ? selectedFir.bhaNumber : "",
      runNumber: selectedFir ? selectedFir.runNumber : "",
      rig: selectedFir ? selectedFir.rig : "",
      wellName: selectedFir ? selectedFir.wellName : "",
      client: selectedFir ? selectedFir.client : "",
      holeSize: selectedFir ? selectedFir.holeSize : "",
      firNumber: selectedFir ? selectedFir.firNumber : "",
      bitGrading: selectedFir ? selectedFir.bitGrading : "",
      tfa: selectedFir ? selectedFir.tfa : "",
      bitType: selectedFir ? selectedFir.bitType : "",
      offBtmPressure: selectedFir ? selectedFir.offBtmPressure : "",
      bitMaker: selectedFir ? selectedFir.bitMaker : "",
      iadc: selectedFir ? selectedFir.iadc : "",
      bitModel: selectedFir ? selectedFir.bitModel : "",
      slackOffWeight: selectedFir ? selectedFir.slackOffWeight : "",
      timelineAndCorrective: selectedFir ? selectedFir.timelineAndCorrective : "",
      onBtmPressure: selectedFir ? selectedFir.onBtmPressure : "",
      flowRate: selectedFir ? selectedFir.flowRate : "",
      offBtmTorque: selectedFir ? selectedFir.offBtmTorque : "",
      wob: selectedFir ? selectedFir.wob : "",
      onBtmTorque: selectedFir ? selectedFir.onBtmTorque : "",
      pickUpWeight: selectedFir ? selectedFir.pickUpWeight : "",
      runUpload: selectedFir ? selectedFir.runUpload : null,
      mudreportUpload: selectedFir ? selectedFir.mudreportUpload : null,
      bhaUpload: selectedFir ? selectedFir.bhaUpload : null,
      incidentType: selectedFir ? selectedFir.incidentType : "",
      operationAtTimeOfIncident: selectedFir ? selectedFir.operationAtTimeOfIncident : "",
      jarring: selectedFir ? selectedFir.jarring : false,
      lcm: selectedFir ? selectedFir.lcm : false,
      dd1: selectedFir ? selectedFir.dd1 : "",
      dd2: selectedFir ? selectedFir.dd2 : "",
      mwd1: selectedFir ? selectedFir.mwd1 : "",
      mwd2: selectedFir ? selectedFir.mwd2 : "",
      incidentSummary: selectedFir ? selectedFir.incidentSummary : "",
      fieldInvest: selectedFir ? selectedFir.fieldInvest : "",
      pvUpload: selectedFir ? selectedFir.pvUpload : null,
      mluUpload: selectedFir ? selectedFir.mluUpload : null,
      firstName: selectedFir ? selectedFir.firstName : "",
      lastName: selectedFir ? selectedFir.lastName : "",
      employeeNumber: selectedFir ? selectedFir.employeeNumber : "",
      otherUpload: selectedFir ? selectedFir.otherUpload : "",
  };
}
