import * as Yup from "yup";

export function FirVal() {
    return Yup.object().shape({
        submissionDate: Yup.date().required(),
        signedDocument: Yup.mixed().required(),
        jobNumber: Yup.string().required(),
        bhaNumber: Yup.number().required(),
        runNumber: Yup.number().required(),
        rig: Yup.string().required(),
        wellName: Yup.string().required(),
        client: Yup.string().required(),
        holeSize: Yup.string().required(),
        firNumber: Yup.string().required(),
        bitGrading: Yup.string().required(),
        tfa: Yup.string().required(),
        bitType: Yup.string().required(),
        offBtmPressure: Yup.number().required(),
        bitMaker: Yup.string().required(),
        iadc: Yup.string().required(),
        bitModel: Yup.string().required(),
        slackOffWeight: Yup.number().required(),
        timelineAndCorrective: Yup.string().required(),
        onBtmPressure: Yup.number().required(),
        flowRate: Yup.number().required(),
        offBtmTorque: Yup.number().required(),
        wob: Yup.number().required(),
        onBtmTorque: Yup.number().required(),
        pickUpWeight: Yup.number().required(),
        runUpload: Yup.mixed().required(),
        mudreportUpload: Yup.mixed().required(),
        bhaUpload: Yup.mixed().required(),
        incidentType: Yup.string().required(),
        operationAtTimeOfIncident: Yup.string().required(),
        jarring: Yup.string().required(),
        lcm: Yup.string().required(),
        dd1: Yup.string().required(),
        dd2: Yup.string().required(),
        mwd1: Yup.string().required(),
        mwd2: Yup.string().required(),
        incidentSummary: Yup.string().required(),
        fieldInvest: Yup.string().required(),
        pvUpload: Yup.mixed().required(),
        mluUpload: Yup.mixed().required(),
        firstName: Yup.string().required(),
        lastName: Yup.string().required(),
        employeeNumber: Yup.string().required(),
    });
}
