import * as Yup from "yup";
export function ToolOrderVal() {
    return Yup.object().shape({
    date: Yup.date().required(),
    jobnumber: Yup.string().required(),
    revision: Yup.number().required(),
    jobtype: Yup.string().required(),
    motortype: Yup.string().required(),
    toolsize: Yup.string().required(),
    topconnection: Yup.string().required(),
    client: Yup.string().required(),
    rigname: Yup.string().required(),
    requiredshippingdate: Yup.date().required(),
    deviated: Yup.string().required(),
    bearingtype: Yup.string().required(),
    sleevestabsize: Yup.string().required(),
    bottomconnection: Yup.string().required(),
    lobeconfig: Yup.string().required(),
    numberofstage: Yup.string().required(),
    rubbertype: Yup.string().required(),
    bendangle: Yup.number().required(),
    pulser: Yup.string().required(),
    mwd: Yup.string().required(),
    nmdccollarsize: Yup.string().required(),
    gamma: Yup.string().required(),
    resistivity: Yup.string().required(),
    density: Yup.string().required(),
    depthfrom: Yup.number().required(),
    depthto: Yup.number().required(),
    flowratemin: Yup.number().required(),
    flowratemax: Yup.number().required(),
    batterytype: Yup.string().required(),
    orderedby: Yup.string().required(),
    motortechnician: Yup.string().required(),
    mwldwtechnician: Yup.string().required(),
    approvedby: Yup.string().required(),
    approvedbydate: Yup.date().required(),
    expectedbtmholetemp: Yup.number().required(),
    mwdbottomcon: Yup.string().required(),
    mwdtopcon: Yup.string().required(),
  });
}